# trading_signals/signal_store.py
# REQ-SIGNALS-005b: Persistent signal history and accuracy tracking
# BLP-031: Self-Improvement through historical performance measurement

"""
SQLite-backed store for trading signal persistence and accuracy tracking.

Schema:
  signals(signal_id TEXT PK, asset TEXT, signal_type TEXT, confidence REAL,
          timestamp TEXT, risk_level TEXT, reasoning TEXT,
          outcome TEXT NULL, outcome_timestamp TEXT NULL)

Retention: 90-day rolling window; aggregated accuracy stats preserved indefinitely.
"""

import sqlite3
import os
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List, Optional
from contextlib import contextmanager


# Default DB path relative to this file's parent package directory
_DEFAULT_DB_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data",
    "signal_history.db",
)


class SignalStore:
    """
    SQLite-backed persistence for trading signals.

    REQ-SIGNALS-005b: Persist every generated signal and record outcomes
                      so get_signal_accuracy() can return real metrics.
    BLP-031: Self-Improvement — accuracy metrics drive future strategy tuning.

    Thread-safety: Uses WAL mode + connection-per-call pattern to support
    concurrent reads from the MCP server while the scheduler is writing.
    """

    def __init__(self, db_path: Optional[str] = None) -> None:
        self.db_path = db_path or _DEFAULT_DB_PATH
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        self._init_db()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @contextmanager
    def _conn(self):
        """Context manager that yields a WAL-mode connection and commits on exit."""
        conn = sqlite3.connect(self.db_path, timeout=10)
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA foreign_keys=ON")
        conn.row_factory = sqlite3.Row
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()

    def _init_db(self) -> None:
        """Create schema if not present. Idempotent."""
        with self._conn() as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS signals (
                    signal_id         TEXT PRIMARY KEY,
                    asset             TEXT NOT NULL,
                    signal_type       TEXT NOT NULL,
                    confidence        REAL NOT NULL,
                    risk_level        TEXT NOT NULL,
                    reasoning         TEXT NOT NULL,
                    timestamp         TEXT NOT NULL,
                    outcome           TEXT,           -- "correct" | "incorrect" | NULL
                    outcome_timestamp TEXT
                )
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_signals_asset ON signals(asset)")
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON signals(timestamp)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_signals_type ON signals(signal_type)"
            )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def save_signal(self, signal: Any) -> None:
        """
        Persist a generated TradingSignal to the store.

        Accepts either a TradingSignal dataclass instance or a plain dict
        (for flexibility when called from non-dataclass contexts).

        REQ-SIGNALS-005b: Every signal generated by SignalGenerator must be saved.
        """
        if hasattr(signal, "__dataclass_fields__"):
            # TradingSignal dataclass
            sid = signal.signal_id
            asset = signal.asset
            signal_type = signal.signal_type
            confidence = float(signal.confidence)
            risk_level = signal.risk_level
            reasoning = signal.reasoning
            timestamp = signal.timestamp
        else:
            sid = signal["signal_id"]
            asset = signal["asset"]
            signal_type = signal["signal_type"]
            confidence = float(signal["confidence"])
            risk_level = signal.get("risk_level", "medium")
            reasoning = signal.get("reasoning", "")
            timestamp = signal.get("timestamp", datetime.now(timezone.utc).isoformat())

        with self._conn() as conn:
            conn.execute(
                """
                INSERT OR IGNORE INTO signals
                    (signal_id, asset, signal_type, confidence, risk_level,
                     reasoning, timestamp)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (sid, asset, signal_type, confidence, risk_level, reasoning, timestamp),
            )

        print(f"[SignalStore] Saved signal {sid[:8]}... | {asset} {signal_type} @{confidence:.1f}%")

    def record_outcome(self, signal_id: str, actual_outcome: str) -> None:
        """
        Record the actual outcome for a previously stored signal.

        Args:
            signal_id: UUID of the signal to update.
            actual_outcome: "correct" if the signal was right, "incorrect" otherwise.

        REQ-SIGNALS-005b: Outcome recording enables accuracy calculation.
        """
        if actual_outcome not in ("correct", "incorrect"):
            raise ValueError(f"actual_outcome must be 'correct' or 'incorrect', got {actual_outcome!r}")

        now = datetime.now(timezone.utc).isoformat()
        with self._conn() as conn:
            conn.execute(
                """
                UPDATE signals
                SET outcome = ?, outcome_timestamp = ?
                WHERE signal_id = ?
                """,
                (actual_outcome, now, signal_id),
            )

    def get_accuracy_metrics(self, days: int = 30) -> Dict[str, Any]:
        """
        Calculate accuracy metrics over a rolling window.

        Returns:
            {
                "total_signals": int,
                "signals_with_outcome": int,
                "accuracy": float,           # 0.0 – 1.0
                "by_asset": {"BTC": {"accuracy": 0.58, "count": 42}, ...},
                "by_signal_type": {"buy": {"accuracy": 0.60, "count": 18}, ...},
                "period_start": str,
                "period_end": str,
            }

        REQ-SIGNALS-005b: Feeds get_signal_accuracy() MCP tool.
        BLP-031: Self-Improvement — accuracy data drives strategy updates.
        """
        period_start = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
        period_end = datetime.now(timezone.utc).isoformat()

        with self._conn() as conn:
            # Overall totals
            row = conn.execute(
                """
                SELECT
                    COUNT(*) AS total,
                    SUM(CASE WHEN outcome IS NOT NULL THEN 1 ELSE 0 END) AS with_outcome,
                    SUM(CASE WHEN outcome = 'correct' THEN 1 ELSE 0 END) AS correct
                FROM signals
                WHERE timestamp >= ?
                """,
                (period_start,),
            ).fetchone()

            total = row["total"] or 0
            with_outcome = row["with_outcome"] or 0
            correct = row["correct"] or 0
            accuracy = (correct / with_outcome) if with_outcome > 0 else 0.0

            # By asset
            by_asset: Dict[str, Any] = {}
            for r in conn.execute(
                """
                SELECT asset,
                       COUNT(*) AS cnt,
                       SUM(CASE WHEN outcome = 'correct' THEN 1 ELSE 0 END) AS c,
                       SUM(CASE WHEN outcome IS NOT NULL THEN 1 ELSE 0 END) AS w
                FROM signals
                WHERE timestamp >= ?
                GROUP BY asset
                """,
                (period_start,),
            ).fetchall():
                by_asset[r["asset"]] = {
                    "count": r["cnt"],
                    "accuracy": (r["c"] / r["w"]) if r["w"] > 0 else 0.0,
                    "signals_with_outcome": r["w"],
                }

            # By signal type
            by_type: Dict[str, Any] = {}
            for r in conn.execute(
                """
                SELECT signal_type,
                       COUNT(*) AS cnt,
                       SUM(CASE WHEN outcome = 'correct' THEN 1 ELSE 0 END) AS c,
                       SUM(CASE WHEN outcome IS NOT NULL THEN 1 ELSE 0 END) AS w
                FROM signals
                WHERE timestamp >= ?
                GROUP BY signal_type
                """,
                (period_start,),
            ).fetchall():
                by_type[r["signal_type"]] = {
                    "count": r["cnt"],
                    "accuracy": (r["c"] / r["w"]) if r["w"] > 0 else 0.0,
                    "signals_with_outcome": r["w"],
                }

        return {
            "total_signals": total,
            "signals_with_outcome": with_outcome,
            "accuracy": round(accuracy, 4),
            "by_asset": by_asset,
            "by_signal_type": by_type,
            "period_start": period_start,
            "period_end": period_end,
            "period_days": days,
        }

    def get_recent(self, limit: int = 50, asset: Optional[str] = None) -> List[Dict[str, Any]]:
        """
        Return recent signals for MCP tool response.

        Args:
            limit: Maximum number of signals to return.
            asset: If provided, filter to this asset only.

        Returns list of dicts suitable for JSON serialization.
        """
        with self._conn() as conn:
            if asset:
                rows = conn.execute(
                    """
                    SELECT * FROM signals
                    WHERE asset = ?
                    ORDER BY timestamp DESC
                    LIMIT ?
                    """,
                    (asset, limit),
                ).fetchall()
            else:
                rows = conn.execute(
                    """
                    SELECT * FROM signals
                    ORDER BY timestamp DESC
                    LIMIT ?
                    """,
                    (limit,),
                ).fetchall()

        return [dict(r) for r in rows]

    def cleanup_old(self, retention_days: int = 90) -> int:
        """
        Delete signals older than retention_days.

        Returns count of deleted rows.
        Called by the scheduler SFA at the start of each run.
        """
        cutoff = (datetime.now(timezone.utc) - timedelta(days=retention_days)).isoformat()
        with self._conn() as conn:
            cursor = conn.execute(
                "DELETE FROM signals WHERE timestamp < ?", (cutoff,)
            )
            deleted = cursor.rowcount

        if deleted > 0:
            print(f"[SignalStore] Cleaned up {deleted} signals older than {retention_days} days")
        return deleted

    def count(self) -> int:
        """Return total number of signals in the store. Useful for health checks."""
        with self._conn() as conn:
            return conn.execute("SELECT COUNT(*) FROM signals").fetchone()[0]
